site_name: DocuSite
theme:
  name: material
  favicon: img/favicon.ico
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - css/custom.css
nav:
  - Home: index.md
  - Links: page2.md
  - Stakeholders: page3.md

# Password on by default.
plugins:
  - encryptcontent:
     global_password: 'password'
     title_prefix: ''
     summary: 'Enter your password:'
     remember_password: true
     session_duration: 60
  - live-edit:
     websockets_host: hostname
     websockets_port: 9999
     debug_mode: true